// Auto-generated by Modern CS Bridge for Unity
// Provides the polyfill required for C# record / init syntax.
#if !NET8_0_OR_GREATER
// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices
{
    internal sealed partial class IsExternalInit { }
}
#endif
